### ISSUE TITLE
NPE for some users when running /csn history

### ISSUE THREAD

**Issue by Phoenix616** [Phoenix616/ChestShopNotifier#2]
Errorlog:
```

[22:11:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'csn' in plugin ChestShopNotifier v1.1.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6d16e64-87b9f46]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6d16e64-87b9f46]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-87b9f46]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(String.java:2227) ~[?:1.8.0_05]
        at com.wfector.command.History.showResults(History.java:143) ~[?:?]
        at com.wfector.command.CommandRunner.Process(CommandRunner.java:147) ~[?:?]
        at com.wfector.notifier.ChestShopNotifier.onCommand(ChestShopNotifier.java:173) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6d16e64-87b9f46]
        ... 15 more

```

Users: dr3gam3r, foozbump

**Comment by Phoenix616** [comment]
Fixed with a2e9ece
