### ISSUE TITLE
Issue that repeatedly pops up on my server startup

### ISSUE THREAD

**Issue by 1ronChef** [Phoenix616/ChestShopNotifier#26]
Not exactly sure what's causing this, if anyone knows please help !
May just be an issue with how I set it up, may be an ignored issue, honestly IDK.

```
17.01 15:02:03 [Server] WARN Plugin ChestShopNotifier v1.3.0-SNAPSHOT (build #36) generated an exception while executing task 61 
17.01 15:02:03 [Server] INFO com.wfector.lib.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure 
17.01 15:02:03 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.HikariPool.<init>(HikariPool.java:105) ~[?:?]
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.notifier.ChestShopNotifier.getConnection(ChestShopNotifier.java:215) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:102) ~[?:?] 
17.01 15:02:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] 
17.01 15:02:03 [Server] INFO Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure 
17.01 15:02:03 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:341) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?] 
17.01 15:02:03 [Server] INFO ... 10 more 
17.01 15:02:03 [Server] INFO Caused by: java.net.ConnectException: Connection refused (Connection refused) 
17.01 15:02:03 [Server] INFO at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181] 
17.01 15:02:03 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[patched_1.13.2.jar:git-Paper-498] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:341) ~[?:?] 
17.01 15:02:03 [Server] INFO at com.wfector.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
```

**Comment by Phoenix616** [comment]
Does that happen after the plugin worked already or does it just not work? If the second one is the case then you probably have an issue in your database setup because this looks like it can't connect to your database server. (Or it's suddenly refusing connections to it)

**Comment by 1ronChef** [comment]
Ah so I need to set up the db for it.... 
Any chance of getting help to do so?
Discord or such methods ?

**Comment by Phoenix616** [comment]
There are tons of guides available online on how to setup a MySQL database. (most linux distributions even come with one pre-installed) Then just enter the values in the config after you setup the database and user.
