### ISSUE TITLE
SQLException: No operations allowed after statement closed.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ChestShopNotifier#6]
ChestShopNotifier 1.1.5

```
[08:31:30] [Craft Scheduler Thread - 26/WARN]: java.sql.SQLException: No operations allowed after statement closed.
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:438)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.StatementImpl.resetCancelledState(StatementImpl.java:912)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1299)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:214)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[08:31:30] [Craft Scheduler Thread - 26/WARN]: Exception in thread "Craft Scheduler Thread - 26" 
[08:31:30] [Craft Scheduler Thread - 26/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShopNotifier v1.1.5 generated an exception while executing task 221
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:223)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

```

Same thing occurs on 1.10.
```
[04:01:31] [Craft Scheduler Thread - 8/WARN]: java.sql.SQLException: No operations allowed after statement closed.
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:438)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1294)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:214)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[04:01:31] [Craft Scheduler Thread - 8/WARN]: Exception in thread "Craft Scheduler Thread - 8" 
[04:01:31] [Craft Scheduler Thread - 8/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShopNotifier v1.1.5 generated an exception while executing task 131
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.wfector.notifier.ChestShopNotifier$2.run(ChestShopNotifier.java:223)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**Comment by Phoenix616** [comment]
Fixed in 2330b2a6
